RoleBase/Controllers/FunctionController.cs
using Login.Service;
using Login.VO;
using RoleBase.ActionFilters;
using RoleBase.CurrentStatus;
using RoleBase.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RoleBase.Controllers
{
    public class FunctionController : Controller
    {
        #region 屬性

        IFunctionService _functionService;
        IRoleService _roleService;

        ILoginService _loginService;
        ISecurityService _securityService;

        private HttpContextBase _currentHttpContext;

        public HttpContextBase CurrentHttpContext
        {
            get
            {
                if (_currentHttpContext != null)
                    return _currentHttpContext;

                return HttpContextFactory.GetHttpContext();
            }
            set { _currentHttpContext = value; }
        }

        private SecurityLevel _currentUserInfo;

        public SecurityLevel CurrentSecurityLevel
        {
            get
            {
                if (_currentUserInfo != null)
                    return _currentUserInfo;

                return SessionConnectionPool.GetCurrentUserInfo;
            }
            set
            {
                if (HttpContext != null)
                    SessionConnectionPool.SetCurrentUserInfo(value);
                else
                    SessionConnectionPool.SetCurrentUserInfo(CurrentHttpContext, value);
                _currentUserInfo = value;
            }
        }

        #endregion

        #region 建構子

        public FunctionController()
        {
            _functionService = RouteConfig.Container.Resolve<IFunctionService, FunctionService>();
            _roleService = RouteConfig.Container.Resolve<IRoleService, RoleService>();
            _loginService = RouteConfig.Container.Resolve<ILoginService, LoginService>();
            _securityService = RouteConfig.Container.Resolve<ISecurityService, SecurityService>();
        }

        public FunctionController(IFunctionService functionService, IRoleService roleService, ILoginService loginService, ISecurityService securityService)
        {
            _functionService = functionService;
            _roleService = roleService;
            _loginService = loginService;
            _securityService = securityService;
        }

        #endregion

        #region Action

        /// <summary>
        /// 取得選單資料
        /// </summary>
        /// <returns></returns>
        public ActionResult GetFunctionMenu(string userID)
        {
            var data = _functionService.GetFunctionNode(userID);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Function管理介面
        /// </summary>
        /// <returns></returns>
        [UserSession]
        public ActionResult FunctionManagement()
        {
            return View("FunctionManagement");
        }

        /// <summary>
        /// Function新增、修改、刪除畫面
        /// </summary>
        /// <returns></returns>
        [UserSession]
        public ActionResult FunctionAddEditDelete()
        {
            // var functionData = _functionService.GetFunctionData();
            return View("FunctionAddEditDelete");
        }

        /// <summary>
        /// 查詢功能
        /// </summary>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult QueryFunction(PageDataVO pageDataVO)
        {
            FunctionTableResultVO result = new FunctionTableResultVO();
            result.FunctionData = _functionService.GetFunctionData(pageDataVO);
            result.TableMaxPage = pageDataVO.AllPageNumber;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 取得作為上層的keyValue資料
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FunctionGetParentData()
        {
            var parentData = _functionService.GetParentKeyValue();

            return Json(parentData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增Function
        /// </summary>
        /// <param name="functionVO"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult AddFunction(FunctionVO functionVO)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                functionVO.Message = "請填寫必填欄位";
            }
            else
            {
                var result = _functionService.AddFunction(functionVO);

                if (!string.IsNullOrEmpty(result))
                {
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    functionVO.Message = result;
                }
                else
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            }
            return Json(functionVO, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 刪除Function
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult DeleteFunction(string id)
        {
            var result = _functionService.DeleteFunction(id);

            if (!string.IsNullOrEmpty(result))
            {
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 編輯Function
        /// </summary>
        /// <param name="functionVO"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult EditFunction(FunctionVO functionVO)
        {
            var result = _functionService.EditFunction(functionVO);
            SessionReflash();

            if (!string.IsNullOrEmpty(result))
            {
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 轉到編輯角色功能關聯的畫面
        /// </summary>
        /// <returns></returns>
        [UserSession]
        public ActionResult RoleFunctionEdit()
        {
           //var roleData = _roleService.GetRoleData();
            return View("RoleFunctionEdit");
        }

        /// <summary>
        /// 查詢腳色資料
        /// </summary>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult QueryRoleFunctionEditRole(PageDataVO pageDataVO)
        {
            RoleTableResultVO result = new RoleTableResultVO();
            result.RoleData = _roleService.GetRoleData(pageDataVO);
            result.TableMaxPage = pageDataVO.AllPageNumber;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 透過角色ID取得勾選的功能資料
        /// 編輯角色與功能的關係
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult GetFunctionByRole(string id, PageDataVO pageDataVO)
        {
            var functionCheckData = _functionService.GetFunctionCheckByRole(id, pageDataVO);
            return Json(functionCheckData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 儲存RoleFunction設定的變更
        /// </summary>
        /// <param name="functionCheckVO"></param>
        /// <param name="roleID"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult SaveRoleFunctionSetting(IEnumerable<FunctionCheckVO> functionCheckVO, string roleID = null)
        {
            string result = string.Empty;

            if (roleID == null)
            {
                //處理有關選時的行為
                result = _functionService.SaveRoleFunctionSetting(functionCheckVO);

                if (!string.IsNullOrEmpty(result))
                {
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            }
            else
            {
                //處理清空所有check時的行為
                result = _functionService.ClearRoleFunctionByRoleID(roleID);

                if (!string.IsNullOrEmpty(result))
                {
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            }
            SessionReflash();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 刷新權限Sesstion
        /// </summary>
        public void SessionReflash()
        {
            SecurityLevel securityLevel = new SecurityLevel();
            AccountInfoData userInfoData = new AccountInfoData()
            {
                UserId = Convert.ToInt32(CurrentHttpContext.Session["UserID"]),
                AccountName = CurrentHttpContext.Session["AccountName"].ToString()
            };

            securityLevel.UserData = userInfoData;
            securityLevel.SecurityRole = _loginService.GetRoleDataByUserID(CurrentHttpContext.Session["UserID"].ToString()).ToList();

RoleBase/Controllers/RoleController.cs
using Login.Service;
using Login.VO;
using RoleBase.ActionFilters;
using RoleBase.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RoleBase.Controllers
{
    public class RoleController : Controller
    {
        #region 屬性

        IRoleService _roleService;

        private HttpContextBase _currentHttpContext;

        public HttpContextBase CurrentHttpContext
        {
            get
            {
                if (_currentHttpContext != null)
                    return _currentHttpContext;

                return HttpContextFactory.GetHttpContext();
            }
            set { _currentHttpContext = value; }
        }
        #endregion

        #region 建構子

        public RoleController()
        {
            _roleService = RouteConfig.Container.Resolve<IRoleService, RoleService>();
        }

        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        #endregion

        #region Action

        /// <summary>
        /// Role管理畫面
        /// </summary>
        /// <returns></returns>
        [UserSession]
        public ActionResult RoleManagement()
        {
            return View("RoleManagement");
        }

        /// <summary>
        /// Role新增、修改、刪除畫面
        /// </summary>
        /// <returns></returns>
        [UserSession]
        public ActionResult RoleAddEditDelete()
        {
            return View("RoleAddEditDelete");
        }

        /// <summary>
        /// 查詢腳色資料
        /// </summary>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult QueryRole(PageDataVO pageDataVO)
        {        
            RoleTableResultVO result = new RoleTableResultVO();
            result.RoleData = _roleService.GetRoleData(pageDataVO);
            result.TableMaxPage = pageDataVO.AllPageNumber;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 新增Role
        /// </summary>
        /// <param name="roleVO"></param>
        /// <returns></returns>
        [HttpPost]
        [UserSession]
        public ActionResult AddRole(RoleVO roleVO)
        {
            if (!ModelState.IsValid)
            {
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                roleVO.Message = "請填寫必填欄位";
            }
            else
            {
                var result = _roleService.AddRole(roleVO);

                if (!string.IsNullOrEmpty(result))
                {
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    roleVO.Message = result;
                }
                else
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            }
            return Json(roleVO, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 刪除Role
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult DeleteRole(string id)
        {
            var result = _roleService.DeleteRole(id);

            if (!string.IsNullOrEmpty(result))
            {
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 編輯Role
        /// </summary>
        /// <param name="roleVO"></param>
        /// <returns></returns>
        [HttpPost]
        [UserSession]
        public ActionResult EditRole(RoleVO roleVO)
        {
            var result = _roleService.EditRole(roleVO);

            if (!string.IsNullOrEmpty(result))
            {
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 轉到編輯角色使用者關聯的畫面
        /// </summary>
        /// <returns></returns>
        [UserSession]
        public ActionResult RoleUserEdit()
        {
            //var roleData = _roleService.GetRoleData();
            return View("RoleUserEdit");
        }

        /// <summary>
        /// 查詢角色資料
        /// </summary>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult QueryRoleUserEditRole(PageDataVO pageDataVO)
        {
            RoleTableResultVO result = new RoleTableResultVO();
            result.RoleData = _roleService.GetRoleData(pageDataVO);
            result.TableMaxPage = pageDataVO.AllPageNumber;
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 透過角色ID取得勾選的使用者資料
        /// 編輯角色與使用者的關係
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult GetUserByRole(string id, PageDataVO pageDataVO)
        {
            var userCheckData = _roleService.GetUserCheckByRole(id, pageDataVO);
            return Json(userCheckData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 儲存RoleUser設定的變更
        /// </summary>
        /// <param name="userCheckVO"></param>
        /// <returns></returns>
        [UserSession]
        [HttpPost]
        public ActionResult SaveRoleUserSetting(IEnumerable<UserCheckVO> userCheckVO, string roleID = null)
        {
            string result = string.Empty;

            if (roleID == null)
            {
                //處理有關聯時的行為
                result = _roleService.SaveRoleUserSetting(userCheckVO);

                if (!string.IsNullOrEmpty(result))
                {
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            }
            else
            {
                //處理清空所有check時的行為
                result = _roleService.ClearRoleUserByRoleID(roleID);

                if (!string.IsNullOrEmpty(result))
                {
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    CurrentHttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

RoleBase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/layoutContext.css" rel="stylesheet" />
    <link href="~/Content/menuStyle.css" rel="stylesheet" />
    <link href="~/Content/TableOrderBy.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/extensionJavascriptFindMethod.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                @Html.ActionLink("後臺管理系統", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="col-md-6">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#">功能1 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">功能2</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">功能3</a>
                            </li>
                            @if (Session["LoginInfo"] != null)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        帳號管理
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                        @Html.ActionLink("角色管理", "RoleManagement", "Role", new { area = "" }, new { @class = "dropdown-item" })
                                        @Html.ActionLink("功能管理", "FunctionManagement", "Function", new { area = "" }, new { @class = "dropdown-item" })

                                        @*<div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Something else here</a>*@
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                    <div class="col-md-6">
                        @if (Session["LoginInfo"] != null)
                        {
                            @Html.ActionLink("登出", "Logout", "Account", new { area = "" }, new { @class = "mx-3 btn btn-primary float-right" })
                            <label class="float-right" style="color:white">您好! @Session["UserName"]</label>
                            <label id="userID" hidden="hidden">@Session["UserID"]</label>
                        }
                        else
                        {
                            @Html.ActionLink("註冊", "Regist", "Account", new { area = "" }, new { @class = "btn btn-primary float-right" })
                            @Html.ActionLink("登入", "Login", "Account", new { area = "" }, new { @class = "mx-3 btn btn-primary float-right" })
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul id="rolebase-nav-menu">
                </ul>
            </div>
            <div class="col-md-10">@RenderBody()</div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/bootstrap.js"></script>
</body>


<script>
    (function () {
        // 取得選單資料
         $.ajax({
             type: "POST",
            url: "@Url.Action("GetFunctionMenu", "Function")",
            data: JSON.stringify({
                "userID": $('#userID').text()
            }),
            contentType: "application/json; charset=utf-8",
            dataType: "json"
        }).done(function (data) {

            GernerateMenu(data, $('#rolebase-nav-menu'));
            Setting();
        }).fail(function (data) {
            if (data.responseJSON != undefined) {
                var Message = data.responseJSON;
                console.log(Message);
                alert("fail Message:" + Message);
            }
            else {
                 window.location.href = "@Url.Action("ErrorPage", "Home")";
                 // window.location.href = data.responseText;
            }
        });

    })();

        function GernerateMenu(data, element) {
            if (data === null)
                return;
            else {
                for (var i = 0; i < data.length; i++) {
                    //alert(data[i].Val.FunctionID);
                    // 處理第一筆資料

                    if (data[i].Next !== null) {
                        var li = $('<li class="rolebase-menu-parent"></li>');

                        var span = $('<span class= "rolebase-menu-node" > <a href="/' + data[i].Val.Url + '">' + data[i].Val.Title + '</a></span >');

                        var ul = $('<ul class="rolebase-sub-menu">');

                        GernerateMenu(data[i].Next, ul);
                        li.append([span, ul]);
                        element.append(li);
                    } else {
                         var li = $('<li></li>');
                        var a = $('<a href="/' + data[i].Val.Url + '">' + data[i].Val.Title + '</a>');
                        li.append(a);
                        element.append(li);
                    }
                }
            }
    }

    function Setting() {
        var toggler = document.getElementsByClassName("rolebase-menu-node");
        var i;

        for (i = 0; i < toggler.length; i++) {
            toggler[i].addEventListener("click", function () {
                this.parentElement.querySelector(".rolebase-sub-menu").classList.toggle("active");
                this.classList.toggle("rolebase-menu-node-opec");
            });
        }
    };

</script>
</html>